name: Solar System Workflow

on: 
  workflow_dispatch:
  # push:
    # branches:
    #   - main
    #   - 'feature/*'

env:
  MONGO_URI: mongo-url #hardcode mongo url here
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }} #create mongo username variable in settings
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }} # create mongo password as a secrets in settings
jobs:
    unit-testing:
        name: Unit Testing
        services:            #defining service container for database
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: 
          MONGO_USERNAME: 
          MONGO_PASSWORD:

        strategy:
          matrix:
            nodejs_version: [18, 20]
            operating_system: [ubuntu-latest, macos-latest]
        runs-on: ${{matrix.operating_system}}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup Node.js environment
          uses: actions/setup-node@v6.2.0
          with:
            node-version: ${{matrix.nodejs_version}}
    
        - name: cache dependency
          uses: actions/cache@v5.0.2
          with: 
            path: node_modules #folder where dependecies are added in the first run
            key:  ${{ runner.os}}-node-modules-${{ hashFiles('package-lock.json') }} #unique key to create a cache and load the cache, here if package-lock.json file amended cache will get invalidated

        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result        # generate test reports
          if: always()
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    code-coverage:
        name: code coverage
        container:        #setting up a job container, we dont need  setup nodejs env step
          image: node:18
        services:            #defining service container for database
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            options:
              -- name mongo  
        env:
          MONGO_URI: 
          MONGO_USERNAME: 
          MONGO_PASSWORD:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        # - name: Setup Node.js environment
        #   uses: actions/setup-node@v6.2.0
        #   with:
        #     node-version: 18

        - name: cache dependency
          uses: actions/cache@v5.0.2
          with: 
            path: node_modules #folder where dependecies are added in the first run
            key:  ${{ runner.os}}-node-modules-${{ hashFiles('package-lock.json') }} #unique key to create a cache and load the cache, here if package-lock.json file amended cache will get invalidated
    
        - name: Install Dependencies
          run: npm install

        - name: code coverage
          continue-on-error: true         #ensuring even if this step, fails, remaining steps will not skip
          run: npm run coverage
          
        - name: Archive Test Result      # generate code coverage reports
          uses: actions/upload-artifact@v3
          with:
            name: code_coverege_result
            path: coverage            #results used to save in coverage folder
            retention-days: 5            #artifact will get deleted after 5 days
    docker:
      name: docker-login
      needs: [unit-testing, code-coverage]
      runs-on: ubuntu-latest
      permissions: 
        packages: write         #providing write access to the secret token which needs to authenticate to ghcr
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Docker Login
          uses: docker/login-action@v3.6.0
          with:
            username: ${{ vars.DOCKER-USERNAME }}
            password: ${{ secrets.DOCKER-PASSWORD }}

        - name: GHCR Login #authenticate with GHCR
          uses: docker/login-action@v3.6.0
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }} #githib account username
            password: ${{ secrets.GITHUB_TOKEN }} #automatically created token which expire after job complete, need write permission

        - name: container registry push 
          uses: docker/build-push-action@v6.18.0
          with:
            context: .  #path where dockerfile is present
            push: true  #whether push image or not
            tags: |
                $ {{vars.DOCKER-USERNAME}}/solar-system:${{ github.sha}}  #tag the image and push to dockerhub
                ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha}}  #tag the image and push to ghcr
    dev-deploy:
      if: contains(github.ref, 'feature/')    #run this job if pushing it from the feature branches
      needs: docker
      uses: ./.github/workflows/reusing-deployment.yml
      secrets:
        k8s-kubeconfig: ${{secrets.KUBECONFIG}}
        mongodb-pwd: ${{secrets.MONGO_PASSWORD}}
      with:
        mongodb-uri: ${{vars.MONGO_URI}}
        environment: development
        k8s-manifest-dir: relative path of dev env
        kubectl-version: provide the rquired version


    dev-integration-testing:
      if: contains(github.ref, 'feature/')    #run this job if pushing it from the feature branches
      name: Dev Integration Testing
      needs: dev-deploy
      runs-on: ubuntu-latest
      steps:
        - name: Test `/live` Endpoint
          env:
            URL: ${{ needs.dev-deploy.outputs.application_url }}
          run: |
            echo "Testing endpoint: https://$URL/live"
            curl https://$URL/live -s -k | jq -r .status | grep -iq live
    prod-deploy:
      if: github.ref == 'refs/heads/main'   #run this job if pushing it from the main branch
      needs: docker
      uses: ./.github/workflows/reusing-deployment.yml
      secrets:
        k8s-kubeconfig: ${{secrets.KUBECONFIG}}
        mongodb-pwd: ${{secrets.MONGO_PASSWORD}}
      with:
        mongodb-uri: ${{vars.MONGO_URI}}
        environment: production
        k8s-manifest-dir: relative path of prod env
        kubectl-version: provide the rquired version
    prod-integration-testing:
      if: github.ref == 'refs/heads/main'   #run this job if pushing it from the main branch
      name: Prod Integration Testing
      needs: prod-deploy
      runs-on: ubuntu-latest
      steps:
        - name: Test `/live` Endpoint
          env:
            URL: ${{ needs.prod-deploy.outputs.application_url }}
          run: |
            echo "Testing endpoint: https://$URL/live"
            curl https://$URL/live -s -k | jq -r .status | grep -iq live